language: perl
perl:
#  - "5.32" # not In Xenial
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"

install:
   - cpanm --quiet --notest Dist::Zilla
   - "dzil authordeps --missing | cpanm --notest "
   - "dzil listdeps --missing | cpanm --notest "

script:
  - dzil smoke --release --author
